# Generated by Django 4.0.2 on 2022-04-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=200)),
                ('urlImg', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('nota', models.FloatField()),
                ('descuento', models.IntegerField()),
                ('generos', models.TextField()),
                ('plataforma', models.CharField(max_length=30)),
                ('tienda', models.CharField(max_length=15)),
            ],
        ),
    ]
