# Generated by Django 4.0.2 on 2022-05-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_gusto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gusto',
            old_name='generosInteresados',
            new_name='generoInteresado',
        ),
    ]
